#!/usr/bin/env perl
use strict;
use warnings;
use Getopt::Long;

my $idx = 0;
GetOptions("1=s" => \$idx);

my %seen;
while (<>) {
    chomp;
    my @c = split(/\t/, $_);
    next if $seen{$c[$idx]||""}++;
    print $_."\n";
}
