#!/usr/bin/env perl
use strict;
use warnings;
use Getopt::Long;

my $col_1 = 0;
GetOptions("1=s" => \$col_1);

my %seen;
while (<>) {
    chomp;
    my @c = split(/\t/, $_);
    next if $seen{$c[$col_1]||""}++;
    print $_."\n";
}
